---
title: "Distance sampling targets pipeline"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../output/rapporten/markdown/algemeen") })
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# set up
library(knitr)
opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  out.width = "100%"
)
opts_knit$set(root.dir = here::here())
```

```{r}
# packages
library(tidyverse)
library(targets)
library(Distance)

library(INBOtheme)
theme_set(theme_inbo(transparent = TRUE))

# Conflicts
conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::select)

# Paths
mbag_dir <- here::here()
targets_store <- file.path(mbag_dir, "source", "targets", "distance_sampling",
                           "_targets")

# Source functions
source(file.path(mbag_dir, "source", "R", "tar_read_ds.R"))
source(file.path(mbag_dir, "source", "R", "plot_pdf_per_cat.R"))
source(file.path(mbag_dir, "source", "R", "plot_detection_curve.R"))
```

# Goal

# Density estimation
## Methods

## Veldleeuwerik
### Data exploration

### Model selection

```{r}
tar_read_ds("aic_comparison", "Veldleeuwerik", 2024,
            store = targets_store) %>%
  select(-species, -year) %>%
  kable()
```

### Model fit

```{r}
final_model <- tar_read_ds("model_selection", "Veldleeuwerik", 2024,
                           store = targets_store)
```

We look at the overal fit of the best model.

```{r}
par(mfrow = c(1, 2))
gof_ds(final_model)
plot(final_model, pdf = TRUE, showpoints = TRUE)
par(mfrow = c(1, 1))
```

```r
plot_pdf_per_cat(final_model)
```

The detection curve(s) look like this:

```{r}
plot_detection_curve(final_model) # add design matrix, ask chat gpt
```

### Results

# Spatial prediction
## Methods

## Veldleeuwerik
### Select response distribution

### Select spatial spline
#### Isotropy


#### Basis dimension

### Model fit

### Predictions
