---
title: "Distance sampling targets pipeline"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../../output/rapporten/markdown/algemeen") })
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# set up
library(knitr)
opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  out.width = "100%"
)
opts_knit$set(root.dir = here::here())
```

```{r}
# packages
library(tidyverse)
library(targets)
library(Distance)

library(INBOtheme)
theme_set(theme_inbo(transparent = TRUE))

# Conflicts
conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::select)

# Paths
mbag_dir <- here::here()
targets_store <- file.path(mbag_dir, "source", "targets", "distance_sampling",
                           "_targets")

# Source functions
source(file.path(mbag_dir, "source", "R", "tar_read_ds.R"))
source(file.path(mbag_dir, "source", "R", "plot_pdf_per_cat.R"))
source(file.path(mbag_dir, "source", "R", "plot_detection_curve.R"))
```

# Goal

```{r}
species_list <- sort(
  c(
    "Veldleeuwerik",
    "Gele Kwikstaart",
    "Geelgors",
    "Kievit",
    "Grasmus",
    "Witte Kwikstaart",
    "Ringmus",
    "Kwartel",
    "Kneu",
    "Torenvalk"
  )
)

mas_data_clean <- tar_read("mas_data_clean", store = targets_store)
year_list <- 2023:max(mas_data_clean$jaar)
```

# Density estimation
## Methods

```{r, results='asis'}
for (sp in species_list) {
  for (y in year_list) {
    params <- list(
      species = sp,
      year = y
    )
    out <- capture.output({
      child <- knitr::knit_child(
        file.path(here::here(), "source", "markdown", "ds_per_species.Rmd"),
        envir = knit_global()
      )
    })
    cat(child, sep = "\n")
  }
}
```

# Spatial prediction
## Methods
