
```{r}
# packages
library(tidyverse)
library(targets)
library(Distance)

library(INBOtheme)
theme_set(theme_inbo(transparent = TRUE))

# Conflicts
conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::select)

# Paths
mbag_dir <- here::here()
targets_store <- file.path(mbag_dir, "source", "targets", "distance_sampling",
                           "_targets")

# Source functions
source(file.path(mbag_dir, "source", "R", "tar_read_ds.R"))
source(file.path(mbag_dir, "source", "R", "plot_pdf_per_cat.R"))
source(file.path(mbag_dir, "source", "R", "plot_detection_curve.R"))
```

## `r params$species` - `r params$year`
### Data exploration

### Model selection

```{r}
final_model <- tar_read_ds("model_selection", params$species, params$year,
                           store = targets_store)
f <- final_model$ddf$ds$aux$ddfobj$scale$formula
key <- ifelse(
  final_model$ddf$ds$aux$ddfobj$type == "hn",
  "half-normal",
  "hazard-rate"
)
```

We select the model with `r key` key function and scale parameter formula `r f`.

```{r}
tar_read_ds("aic_comparison", params$species, params$year,
            store = targets_store) %>%
  select(-species, -year) %>%
  filter(`Delta AIC` <= 10) %>% # only show low AIC models
  kable()
```

### Model fit

We look at the fit of the selected model.

```{r}
par(mfrow = c(1, 2))
gof_ds(final_model)
plot(final_model, pdf = TRUE, showpoints = TRUE)
par(mfrow = c(1, 1))
```

The detection curve(s) look like this:

```{r}
plot_detection_curve(final_model) # add design matrix, ask chat gpt
```

### Results

Detection probabilities.

```{r}
tar_read_ds("detection_probabilities", params$species,
            store = targets_store) %>%
  filter(year == params$year) %>%
  select(-species, -year) %>%
  drop_na() %>%
  relocate("estimate_p", "se_p", "ll_beta", "ul_beta", .after = last_col()) %>%
  kable()
```

#### Stratum

Abundances.

```{r}
abundances_stratum <- tar_read_ds("abundances_stratum", params$species,
                                  store = targets_store)
abundances_stratum %>%
  filter(
    if (params$year == 2023) {
      year == params$year & grepl("^Zandleem|^Leem", Label)
    } else {
      year == params$year
    }
  ) %>%
  select(-species, -year) %>%
  rename("stratum" = "Label", "estimate" = "Estimate") %>%
  kable()
```

Densities.

```{r}
densities_stratum <- tar_read_ds("densities_stratum", params$species,
                                 store = targets_store)
densities_stratum %>%
  filter(
    if (params$year == 2023) {
      year == params$year & grepl("^Zandleem|^Leem", Label)
    } else {
      year == params$year
    }
  ) %>%
  select(-species, -year) %>%
  rename("stratum" = "Label", "estimate" = "Estimate") %>%
  kable()
```

#### Region

Abundances.

```{r}
abundances_region <- tar_read_ds("abundances_region", params$species,
                                 store = targets_store)
abundances_region %>%
  filter(
    if (params$year == 2023) {
      year == params$year & grepl("^Zandleem|^Leem", Label)
    } else {
      year == params$year
    }
  ) %>%
  select(-species, -year) %>%
  rename("region" = "Label", "estimate" = "Estimate") %>%
  kable()
```

Densities.

```{r}
densities_region <- tar_read_ds("densities_region", params$species,
            store = targets_store)
densities_region %>%
  filter(
    if (params$year == 2023) {
      year == params$year & grepl("^Zandleem|^Leem", Label)
    } else {
      year == params$year
    }
  ) %>%
  select(-species, -year) %>%
  rename("region" = "Label", "estimate" = "Estimate") %>%
  kable()
```
