---
title: "Enkele cijfers veldwerk 2024"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# set up
library(knitr)
opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  out.width = "100%"
)
opts_knit$set(root.dir = here::here())
```

```{r}
# packages
library(tidyverse)
library(targets)
library(sf)

# Conflicts
conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::select)

# Paths
mbag_dir <- here::here()
targets_store <- here::here("source", "targets", "data_preparation", "_targets")
```

# Enkele cijfers

We selecteren de MBAG MAS data van 2024.

```{r}
mas_data_clean <- tar_read("mas_data_clean", store = targets_store)
mas_data_2024 <- mas_data_clean %>%
  filter(jaar == 2024)
```

```{r}
aantal_soorten <- mas_data_2024 %>%
  st_drop_geometry() %>%
  distinct(naam) %>%
  nrow()

mas_data_2024_vogels <- mas_data_2024 %>%
  st_drop_geometry() %>%
  filter(soortgrp == 2)

aantal_vogels <- mas_data_2024_vogels %>%
  distinct(naam) %>%
  nrow()

mas_data_2024_zoogdieren <- mas_data_2024 %>%
  st_drop_geometry() %>%
  filter(soortgrp == 1)

aantal_zoogdieren <- mas_data_2024_zoogdieren %>%
  distinct(naam) %>%
  nrow()
```

In totaal zijn `r nrow(mas_data_2024)` waarnemingen gedaan. Er werden in totaal `r aantal_soorten` verschillende soorten gezien, `r aantal_vogels` vogels en `r aantal_zoogdieren` zoogdieren.

```{r}
mas_data_2024 %>%
  st_drop_geometry() %>%
  group_by(regio) %>%
  mutate(
    aantal_soorten = n_distinct(naam),
    aantal_waarnemingen = n()) %>%
  ungroup(regio) %>%
  distinct(regio, aantal_soorten, aantal_waarnemingen) %>%
  arrange(regio) %>%
  kable()
```
