# post_render_cleanup.R
# This script cleans up 09_densiteitsschattingen.qmd after rendering.
main_qmd <- "09_densiteitsschattingen.qmd"

# Read file
lines <- readLines(main_qmd)

# Find the lines to replace
start <- grep("<-- AUTOGENERATED-START -->", lines)
end   <- grep("<-- AUTOGENERATED-END -->", lines)
if (length(start) != 1 || length(end) != 1 || start > end) {
  stop("Markers not found or malformed in QMD")
}

# Add informative message
msg <- c(
  "",
  "> ⚠️ **Let op:** de inhoud onder `## Resultaten` wordt automatisch",
  "> gegenereerd tijdens het renderen via `render_children.R`.",
  "> Pas dit deel niet manueel aan."
)

lines_new <- c(
  lines[1:start],
  msg,
  "",
  lines[end:length(lines)]
)

# Overwrite the file
writeLines(lines_new, main_qmd)


# Flanders qmd post render
flandersqmd::post_render()
