# post_render_cleanup.R
source(file.path("scripts", "clean_autogenerated_qmd.R"))

msg <- c(
  "",
  "> ⚠️ **Let op:** de inhoud hieronder wordt automatisch",
  "> gegenereerd tijdens het renderen via `render_children.R`.",
  "> Pas dit deel niet manueel aan."
)

clean_autogenerated_qmd(
  qmd_file = "09_densiteitsschattingen.qmd",
  message = msg
)

clean_autogenerated_qmd(
  qmd_file = "detection_curves.qmd",
  message = msg
)

clean_autogenerated_qmd(
  qmd_file = "densities_tables.qmd",
  message = msg
)

# Remove folder
unlink("spec_files", recursive = TRUE)


# Flanders qmd post render
flandersqmd::post_render()
