#' Finalise QMD files after rendering
#'
#' Performs post-processing steps on one or more Quarto (`.qmd`) files by
#' inserting a warning message into autogenerated sections and optionally
#' removing temporary child directories.
#'
#' @param target_files Character vector. Paths to QMD files to update.
#' @param message Character vector inserted inside the autogenerated section.
#'   If set to `"default"`, a standard warning message is used.
#' @param child_dirs_rm Character vector of directory paths to remove after
#'   cleanup. Directories are deleted recursively.
#' @param ... Other arguments passed to [autoqmd_cleanup()]
#'
#' @return Invisibly returns `NULL`. Files are modified on disk.
#'
#' @details
#' This function is intended to be called at the end of a Quarto rendering
#' pipeline. It applies [autoqmd_cleanup()] to each file, ensuring that the
#' autogenerated region contains a clear do-not-edit message. Temporary child
#' document directories created during rendering can also be removed if their
#' paths are supplied via `child_dirs_rm`.
#'
#' @seealso [autoqmd_cleanup]
#'
#' @export
#'
#' @importFrom assertthat is.string
#'
#' @examples
#' \dontrun{
#' # Clean up a single QMD file
#' autoqmd_finalise("report.qmd")
#'
#' # Use a custom message
#' autoqmd_finalise(
#'   target_files = "report.qmd",
#'   message = c(
#'     "> Auto-generated content below",
#'     "> Do not edit manually."
#'   )
#' )
#'
#' # Clean multiple files and remove temp directories
#' autoqmd_finalise(
#'   target_files = c("analysis/a.qmd", "analysis/b.qmd"),
#'   child_dirs_rm = c("child_files_a", "child_files_b")
#' )
#' }
autoqmd_finalise <- function(
  target_files,
  message = "default",
  child_dirs_rm = NULL,
  ...
) {
  # Validation
  stopifnot("`target_files` must be a path to QMD files to update." =
              all(sapply(target_files, assertthat::is.string)))
  stopifnot("`target_files` must be a path to QMD files to update." =
              all(sapply(target_files, file.exists)))
  stopifnot("`message` must be a character vector of length." =
              is.character(message))

  # Get message
  if (all(message == "default")) {
    message <- c(
      "",
      "> **Note:** The content below is automatically generated",
      "> during rendering. Do not edit this part manually."
    )
  }

  # Clean up qmd
  lapply(target_files, autoqmd_cleanup, message = message, ...)

  # Remove child documents folder
  unlink(child_dirs_rm, recursive = TRUE)
}
