#' Insert autogenerated child documents into YAML files
#'
#' This function is a helper for [autoqmd_generate_children()]. This function
#' inserts references to autogenerated child documents into a
#' YAML file (`.yml` or `.yaml`). It replaces
#' the lines between marker comments with YAML entries referencing the child
#' documents. These entries can be used, for example, in website sidebars or
#' navigation menus.
#'
#' @param target_file Path to the YAML file to modify (`.yml`, `.yaml`).
#' @param child_files Character vector of file paths to include.
#' @param child_labels Optional character vector of labels corresponding to
#'   `child_files`. If `NULL`, labels are derived from the filenames.
#' @param start_marker Marker string indicating the start of the autogenerated
#'   block. Defaults to `"<!-- AUTOGENERATED-START -->"`.
#' @param end_marker Marker string indicating the end of the autogenerated
#'   block. Defaults to `"<!-- AUTOGENERATED-END -->"`.
#' @param quiet Logical; if `TRUE`, suppresses messages.
#'
#' @return Invisibly returns the modified lines of the target file.
#'   The file is updated on disk.
#'
#' @seealso [autoqmd_generate_children()]
#'
#' @importFrom assertthat is.string
#' @importFrom tools file_path_sans_ext
#'
#' @noRd
autoqmd_insert_yaml <- function(
  target_file,
  child_files,
  child_labels = NULL,
  start_marker = "<!-- AUTOGENERATED-START -->",
  end_marker = "<!-- AUTOGENERATED-END -->",
  quiet = FALSE
) {
  # Validation
  if (!is.null(child_labels)) {
    stopifnot("`child_labels` must be character." =
                all(sapply(child_labels, assertthat::is.string)))
    stopifnot("`child_labels` must match `child_files` in length." =
                length(child_labels) == length(child_files))
  } else {
    child_labels <- tools::file_path_sans_ext(basename(child_files))
  }

  # Read file
  lines <- readLines(target_file)

  # Find markers
  start <- grep(start_marker, lines)
  end   <- grep(end_marker, lines)
  if (length(start) != 1 || length(end) != 1 || start > end) {
    stop(
      "Markers not found or malformed in YAML file: ", target_file,
      ". Use YAML comments such as '# AUTOGENERATED-START'."
    )
  }

  # Determine indentation from the start marker
  indent <- sub("^(\\s*).*", "\\1", lines[start])
  indent_item <- paste0(indent, "  ")
  indent_field <- paste0(indent_item, "  ")

  # Convert paths to use forward slashes
  rel_paths <- gsub("\\\\", "/", child_files)

  # Build YAML sidebar entries
  yaml_entries <- unlist(
    Map(function(label, path) {
      c(
        paste0(indent_item, "- text: ", label),
        paste0(indent_field, "file: ", path)
      )
    }, child_labels, rel_paths)
  )

  # Replace block between markers
  lines_new <- c(
    lines[1:start],
    yaml_entries,
    lines[end:length(lines)]
  )

  # Write back to file
  writeLines(lines_new, target_file)

  if (!quiet) {
    message(
      "Updated autogenerated block in ", target_file,
      " with ", length(child_files), " sidebar entries."
    )
  }

  invisible(lines_new)
}
