#' Insert autogenerated child documents into Quarto files
#'
#' This function inserts references to autogenerated child documents into a
#' Quarto file. It supports both `.qmd` documents and Quarto configuration
#' files (`.yml` or `.yaml`), adapting its behaviour to the file type.
#'
#' For `.qmd` files, the function replaces the lines between
#' `<!-- AUTOGENERATED-START -->` and `<!-- AUTOGENERATED-END -->`
#' with Quarto include directives of the form
#' `{{< include path >}}`. Optionally, LaTeX page breaks
#' (`\\newpage` or `\\clearpage`) can be inserted between includes.
#'
#' For Quarto configuration files such as `_quarto.yml`, the function replaces
#' the lines between marker comments with YAML entries referencing the child
#' documents. These entries can be used, for example, in website sidebars or
#' navigation menus.
#'
#' Marker syntax must match the file type:
#' \itemize{
#'   \item `.qmd` files: `<!-- AUTOGENERATED-START -->` and
#'         `<!-- AUTOGENERATED-END -->`
#'   \item `.yml` or `.yaml` files: `# AUTOGENERATED-START` and
#'         `# AUTOGENERATED-END`
#' }
#'
#' @param target_file Path to the Quarto file to modify. Supported file types
#'   are `.qmd`, `.yml`, and `.yaml`.
#' @param child_files Character vector of file paths to include.
#' @param child_labels Optional character vector of labels corresponding to
#'   `child_files`. These are used in YAML outputs (e.g., Quarto website
#'   sidebars). If `NULL`, labels are derived from the filenames.
#' @param start_marker Marker string indicating the start of the autogenerated
#'   block. Defaults to `"<!-- AUTOGENERATED-START -->"`.
#' @param end_marker Marker string indicating the end of the autogenerated
#'   block. Defaults to `"<!-- AUTOGENERATED-END -->"`.
#' @param page_break Character string specifying a LaTeX page break to
#'   insert between includes. Options: `"newpage"`, `"clearpage"`.
#'   Defaults to `NULL` (no page breaks).
#' @param template Optional path to the QMD template used to generate
#'   the child files. Its modification time will be
#'   tracked.
#' @param template_deps Optional character vector of file paths that are
#'   explicit dependencies of the template (e.g. R scripts, data files).
#'   Their modification times are included in the dependency stamp.
#' @param quiet Logical; if `TRUE`, suppresses messages.
#'
#' @details
#' For `.qmd` files, dependency timestamps derived from `template` and
#' `template_deps` are embedded as invisible HTML comments via
#' [autoqmd_dependency_stamp()]. This ensures that Quarto's `freeze:` mechanism
#' correctly detects when templates or dependencies have changed.
#'
#' @return Invisibly returns the modified lines of the target file.
#'   The file is updated on disk.
#'
#' @seealso [autoqmd_generate_children()], [autoqmd_dependency_stamp()],
#' [autoqmd_prepare()]
#'
#' @export
#'
#' @importFrom assertthat is.string is.flag
#' @importFrom tools file_ext
#'
#' @examples
#' \dontrun{
#' my_species <- paste("Iris", levels(iris$Species))
#'
#' # Create child document for each species
#' # Use freeze to keep child files with label names
#' out_files <- autoqmd_generate_children(
#'   species = my_species,
#'   label = gsub("\\s", ".", tolower(my_species)),
#'   template = "_species_template.qmd",
#'   child_dir = "child_qmd",
#'   freeze = "label"
#' )
#'
#' # Include child files in report with page breaks
#' autoqmd_insert_children(
#'   target_file = "report.qmd",
#'   child_files = out_files,
#'   template = "_species_template.qmd",
#'   template_deps = c("R/load_species_data.R", "data/species_lookup.csv"),
#'   page_break = "newpage"
#' )
#'
#' # Include child files in _quarto.yml
#' autoqmd_insert_children(
#'   target_file  = "_quarto.yml",
#'   child_files  = out_files,
#'   child_labels = my_species,
#'   start_marker = "# AUTOGENERATED-START",
#'   end_marker   = "# AUTOGENERATED-END"
#' )
#' }
autoqmd_insert_children <- function(
  target_file,
  child_files,
  child_labels = NULL,
  start_marker = "<!-- AUTOGENERATED-START -->",
  end_marker = "<!-- AUTOGENERATED-END -->",
  page_break = NULL,
  template = NULL,
  template_deps = NULL,
  quiet = FALSE
) {
  # Validation
  stopifnot("`target_file` must be a path to a Quarto file to modify." =
              assertthat::is.string(target_file))
  stopifnot("`target_file` must be a path to a Quarto file to modify." =
              file.exists(target_file))
  stopifnot("`child_files` must be a path to child files to include." =
              all(sapply(child_files, assertthat::is.string)))
  stopifnot("`child_files` must be a path to child files to include." =
              all(sapply(child_files, file.exists)))
  stopifnot("`start_marker` must be a scalar character vector." =
              assertthat::is.string(start_marker))
  stopifnot("`end_marker` must be a scalar character vector." =
              assertthat::is.string(end_marker))
  stopifnot("`quiet` must be a scalar logical vector." =
              assertthat::is.flag(quiet))

  # Get file extension
  ext <- tolower(tools::file_ext(target_file))

  # Insert child files
  switch(
    ext,
    "qmd" = autoqmd_insert_qmd(
      target_file = target_file,
      child_files = child_files,
      start_marker = start_marker,
      end_marker = end_marker,
      page_break = page_break,
      template = template,
      template_deps = template_deps,
      quiet = quiet
    ),
    "yml" = autoqmd_insert_yaml(
      target_file = target_file,
      child_files = child_files,
      child_labels = child_labels,
      start_marker = start_marker,
      end_marker = end_marker,
      quiet = quiet
    ),
    "yaml" = autoqmd_insert_yaml(
      target_file = target_file,
      child_files = child_files,
      child_labels = child_labels,
      start_marker = start_marker,
      end_marker = end_marker,
      quiet = quiet
    ),
    stop(
      "Unsupported file type: ", target_file,
      ". Only '.qmd', '.yml', and '.yaml' are supported."
    )
  )
}
