#' Insert autogenerated child documents into QMD files
#'
#' This function is a helper for [autoqmd_generate_children()]. The function
#' inserts references to autogenerated child documents into a
#' Quarto file (`.qmd`).It replaces the lines between
#' `<!-- AUTOGENERATED-START -->` and `<!-- AUTOGENERATED-END -->`
#' with Quarto include directives of the form
#' `{{< include path >}}`. Optionally, LaTeX page breaks
#' (`\\newpage` or `\\clearpage`) can be inserted between includes.
#'
#' @param target_file Path to the Quarto file to modify (`.qmd`).
#' @param child_files Character vector of file paths to include.
#' @param start_marker Marker string indicating the start of the autogenerated
#'   block. Defaults to `"<!-- AUTOGENERATED-START -->"`.
#' @param end_marker Marker string indicating the end of the autogenerated
#'   block. Defaults to `"<!-- AUTOGENERATED-END -->"`.
#' @param page_break Character string specifying a LaTeX page break to
#'   insert between includes. Options: `"newpage"`, `"clearpage"`.
#'   Defaults to `NULL` (no page breaks).
#' @param template Optional path to the QMD template used to generate
#'   the child files. Its modification time will be
#'   tracked.
#' @param template_deps Optional character vector of file paths that are
#'   explicit dependencies of the template (e.g. R scripts, data files).
#'   Their modification times are included in the dependency stamp.
#' @param quiet Logical; if `TRUE`, suppresses messages.
#'
#' @details
#' Dependency timestamps derived from `template` and
#' `template_deps` are embedded as invisible HTML comments via
#' [autoqmd_dependency_stamp()]. This ensures that Quarto's `freeze:` mechanism
#' correctly detects when templates or dependencies have changed.
#'
#' @return Invisibly returns the modified lines of the target file.
#'   The file is updated on disk.
#'
#' @seealso [autoqmd_generate_children()], [autoqmd_dependency_stamp()]
#'
#' @importFrom assertthat is.string
#' @importFrom tools file_path_sans_ext
#'
#' @noRd
autoqmd_insert_qmd <- function(
  target_file,
  child_files,
  start_marker = "<!-- AUTOGENERATED-START -->",
  end_marker = "<!-- AUTOGENERATED-END -->",
  page_break = NULL,
  template = NULL,
  template_deps = NULL,
  quiet = FALSE
) {
  # Validation
  stopifnot(
    "page_break must be NULL, 'newpage', or 'clearpage'." =
      is.null(page_break) || page_break %in% c("newpage", "clearpage")
  )
  stopifnot(
    "`template_deps` must be NULL or a character vector of file paths." =
      is.null(template_deps) ||
      (all(sapply(template_deps, assertthat::is.string)) &&
       all(sapply(template_deps, file.exists)))
  )

  # Read file
  lines <- readLines(target_file)

  # Find markers
  start <- grep(start_marker, lines)
  end   <- grep(end_marker, lines)
  if (length(start) != 1 || length(end) != 1 || start > end) {
    stop("Markers not found or malformed in QMD file: ", target_file)
  }

  # Generate dependency timestamps using the helper
  timestamp_line <- autoqmd_dependency_stamp(c(template, template_deps))

  # Build child includes
  if (!is.null(page_break)) {
    # Insert page break between includes, but not after the last one
    include_lines <- paste0("{{< include ", child_files, " >}}")
    child_lines <- paste(
      paste(include_lines, collapse = paste0("\n\n\\", page_break, "\n\n")),
      "\n"
    )
  } else {
    child_lines <- sprintf("{{< include %s >}}\n", child_files)
  }

  # Combine the hidden timestamp and includes
  autogenerated_block <- c(timestamp_line, "", child_lines)

  # Replace block between markers
  lines_new <- c(
    lines[1:start],
    "",
    autogenerated_block,
    lines[end:length(lines)]
  )

  # Write back to file
  writeLines(lines_new, target_file)

  if (!quiet) {
    msg <- paste0("Updated autogenerated block in ", target_file,
                  " with ", length(child_files), " child includes.")
    if (!is.null(page_break)) {
      msg <- paste0(msg, " Page breaks added: \\", page_break, ".")
    }
    message(msg)
  }

  invisible(lines_new)
}
