#' Generate child QMDs and insert them into a parent document
#'
#' This function wraps [`autoqmd_generate_children()`] and
#' [`autoqmd_insert_children()`] to support typical Quarto
#' pre-render workflows: generating child `.qmd` files from a
#' template and inserting the corresponding include directives
#' into a parent QMD.
#'
#' @param ... Named vectors or lists of equal length, passed to
#'   `knitr::knit_expand`. Each position across vectors represents
#'   one document to generate.
#' @param template Path to a Quarto template (`.qmd`) file to expand.
#' @param child_dir Directory where the generated files should be written.
#'   The directory is created if it does not exist.
#' @param target_file Path to the Quarto file to modify. Supported file types
#'   are `.qmd`, `.yml`, and `.yaml`.
#' @param freeze Optional string giving the name of a variable in `...`
#'   whose values will be used for deterministic file names.
#'   If provided, filenames will be of the form `"<value>.qmd"`,
#'   and files will only be regenerated if the template is newer.
#' @param template_deps Optional character vector of file paths that are
#'   explicit dependencies of the template (e.g. R scripts, data files).
#'   Their modification times are included in the dependency stamp.
#' @param delim Character vector of length 2 giving the opening and closing
#'   delimiters used for template variables. Passed to `knitr::knit_expand`.
#'   Defaults to `c("{{", "}}")`, which is convenient for Quarto templates and
#'   avoids conflicts with LaTeX or Pandoc syntax.
#' @param start_marker Marker string indicating the start of the autogenerated
#'   block. Defaults to `"<!-- AUTOGENERATED-START -->"`.
#' @param end_marker Marker string indicating the end of the autogenerated
#'   block. Defaults to `"<!-- AUTOGENERATED-END -->"`.
#' @param page_break Character string specifying a LaTeX page break to
#'   insert between includes. Options: `"newpage"`, `"clearpage"`.
#'   Defaults to `NULL` (no page breaks).
#' @param quiet Logical; if `TRUE`, suppresses messages.
#'
#' @details
#' The function proceeds in two steps:
#'
#' 1. **Generate child documents** using
#'    [`autoqmd_generate_children()`], optionally with
#'    deterministic filenames when `freeze` is used.
#'
#' 2. **Insert include directives** into the parent `.qmd` by replacing
#'    the block between the markers specified by `start_marker` and
#'    `end_marker`.
#'    If a template is provided, dependency timestamps are included
#'    to trigger Quarto's freeze mechanism when relevant.
#'
#' Input files (`template`, `target_file`) and marker presence are validated
#' before generation occurs, preventing unnecessary computation.
#'
#' @return
#' Invisibly returns a list with:
#' \describe{
#'   \item{children}{Paths to the generated child QMD files}
#'   \item{parent}{Path to the updated parent QMD}
#'   \item{dir}{Directory containing child documents}
#' }
#'
#' @seealso [autoqmd_generate_children()], [autoqmd_insert_children()]
#'
#' @export
#'
#' @examples
#' \dontrun{
#' my_species <- paste("Iris", levels(iris$Species))
#'
#' # Create child document for each species
#' # Use freeze to keep child files with label names
#' # Include child files in report
#' autoqmd_prepare(
#'   species = my_species,
#'   label = gsub("\\s", ".", tolower(my_species)),
#'   template = "_species_template.qmd",
#'   child_dir = "child_qmd",
#'   target_file = "report.qmd",
#'   freeze = "label"
#' )
#' }
autoqmd_prepare <- function(
  ...,
  template,
  child_dir,
  target_file,
  freeze = NULL,
  template_deps = NULL,
  delim = c("{{", "}}"),
  start_marker = "<!-- AUTOGENERATED-START -->",
  end_marker = "<!-- AUTOGENERATED-END -->",
  page_break = NULL,
  quiet = FALSE
) {
  # Validate inputs
  if (!file.exists(template)) {
    stop("Template does not exist: ", template)
  }
  if (!file.exists(target_file)) {
    stop("Parent QMD does not exist: ", target_file)
  }

  # Ensure parent file contains the markers before generating anything
  parent_lines <- readLines(target_file)
  if (!any(grepl(start_marker, parent_lines)) ||
        !any(grepl(end_marker,   parent_lines))) {
    stop("Markers not found in parent QMD: ", target_file)
  }

  # Generate child documents from template
  child_files <- autoqmd_generate_children(
    ...,
    template = template,
    child_dir = child_dir,
    freeze = freeze,
    delim = delim,
    quiet = quiet
  )

  # Insert includes
  autoqmd_insert_children(
    target_file = target_file,
    child_files = child_files,
    start_marker = start_marker,
    end_marker = end_marker,
    page_break = page_break,
    template = template,
    template_deps = template_deps,
    quiet = quiet
  )

  # Return useful structured output
  invisible(list(
    children = child_files,
    parent   = target_file,
    dir      = child_dir
  ))
}
