# remotes::install_github("inbo/flandersqmd#57a604d981d85d632db65c98b1abb2e9d032359c")
library(flandersqmd)
library(targets)
source("R/tar_read_mas.R")

# Results chapter 4 by species
target_species <- c(
  "Boerenzwaluw",
  "Geelgors",
  "Gele Kwikstaart",
  "Grasmus",
  "Graspieper",
  "Grutto",
  "Kievit",
  "Kneu",
  "Patrijs",
  "Ringmus",
  "Roodborsttapuit",
  "Scholekster",
  "Torenvalk",
  "Veldleeuwerik",
  "Wulp"
)

## Create child document for each species and
## include child files in report
autoqmd_prepare(
  species = tolower(target_species),
  subtitle = stringr::str_to_sentence(target_species),
  label = gsub("\\s", ".", tolower(target_species)),
  branch = seq_along(target_species),
  template = "_simulatieparameters_per_soort.qmd",
  child_dir = "child_qmd",
  target_file = "04_schatting_simulatieparameters.qmd",
  page_break = "newpage"
)

# Results appendix
scenarios <- tar_read_mas("scenarios")

## Create child document for each species and
## include child files in report
autoqmd_prepare(
  branch = seq_len(nrow(scenarios)),
  template = "_powerplot_per_scenario.qmd",
  child_dir = "child_qmd2",
  target_file = "appendix.qmd",
  start_marker = "AUTOGENERATED-START2",
  end_marker = "AUTOGENERATED-END2"
)
