# Load packages
library(targets)

# Source functions
source("R/tar_read_mas.R")

scripts <- list.files(
  path = "R",
  pattern = "^autoqmd.*\\.R$",
  full.names = TRUE
)
invisible(lapply(scripts, source))

# Results chapter 4 by species
target_species <- c(
  "Boerenzwaluw",
  "Geelgors",
  "Gele Kwikstaart",
  "Grasmus",
  "Graspieper",
  "Grutto",
  "Kievit",
  "Kneu",
  "Patrijs",
  "Ringmus",
  "Roodborsttapuit",
  "Scholekster",
  "Torenvalk",
  "Veldleeuwerik",
  "Wulp"
)

## Create child document for each species and
## include child files in report
autoqmd_prepare(
  species = tolower(target_species),
  subtitle = stringr::str_to_sentence(target_species),
  label = gsub("\\s", ".", tolower(target_species)),
  branch = seq_along(target_species),
  template = "_simulatieparameters_per_soort.qmd",
  child_dir = "child_qmd",
  target_file = "04_schatting_simulatieparameters.qmd",
  page_break = "newpage"
)

# Results appendix
scenarios <- tar_read_mas("scenarios")
scenarios_sigma <- tar_read_mas("scenarios_sigma")

## Create child document for each species and
## include child files in report
autoqmd_prepare(
  branch = c(seq_len(nrow(scenarios)), seq_len(nrow(scenarios_sigma))),
  scen_type = rep(c("power", "sigma"),
                  c(nrow(scenarios), nrow(scenarios_sigma))),
  template = "_powerplot_per_scenario.qmd",
  child_dir = "child_qmd2",
  target_file = "zzz_visualisatie_poweroptimalisatie.qmd",
  start_marker = "AUTOGENERATED-START2",
  end_marker = "AUTOGENERATED-END2"
)
