---
title: "Distance sampling targets pipeline"
author: "Ward Langeraert"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc_depth: 4
    toc: true
    toc_float: true
    toc_collapsed: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# set up
library(knitr)
opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  out.width = "100%"
)
opts_knit$set(root.dir = here::here())
```

```{r}
# packages
library(targets)
```

# Doel

```{r}
species_list <- sort(
  c(
    "Veldleeuwerik",
    "Gele Kwikstaart",
    "Geelgors",
    "Kievit",
    "Grasmus",
    "Witte Kwikstaart",
    "Ringmus",
    "Kwartel",
    "Kneu",
    "Torenvalk"
  )
)

mas_data_clean <- tar_read("mas_data_clean")
year_list <- 2023:max(mas_data_clean$jaar)
```

# Densiteitsschattingen
## Methoden

```{r, results='asis'}
for (sp in species_list) {
  params <- list(
    species = sp,
    years = year_list
  )
  out <- capture.output({
    child <- knitr::knit_child(
      file.path(here::here(), "ds_per_species.Rmd"),
      envir = knit_global()
    )
  })
  cat(child, sep = "\n")
}
```

# Spatiale predicties
## Methoden

## Veldleeuwerik
### Selecteer responsdistributie

### Selecteer spatiale spline
#### Isotropie


#### Basisdimentie

### Model fit

### Predicties
