### `r params$year`
#### Data exploration

#### Model selection

```{r}
final_model <- tar_read_ds("model_selection", params$species, params$year)
f <- final_model$ddf$ds$aux$ddfobj$scale$formula
key <- ifelse(
  final_model$ddf$ds$aux$ddfobj$type == "hn",
  "half-normal",
  "hazard-rate"
)
```

We select the model with `r key` key function and scale parameter formula `r f`.

```{r}
tar_read_ds("aic_comparison", params$species, params$year) %>%
  select(-species, -year) %>%
  filter(`Delta AIC` <= 10) %>% # only show low AIC models
  kable()
```

#### Model fit

We look at the fit of the selected model.

```{r}
par(mfrow = c(1, 2))
gof_ds(final_model)
plot(final_model, pdf = TRUE, showpoints = TRUE)
par(mfrow = c(1, 1))
```

The detection curve(s) look like this:

```{r}
plot_detection_curve(
  final_model,
  show_data = TRUE,
  plot_average_fit = TRUE,
  plot_covariate_fit = TRUE
) +
  scale_y_continuous(limits = c(0, NA), breaks = seq(0, 100, by = 0.25)) +
  labs(x = "Distance (m)", y = "Detection probability") +
  theme_minimal() +
  theme(
    legend.background = element_rect(fill = "white", color = "darkgrey"),
    legend.margin = margin(6, 6, 6, 6),
    legend.position = "bottom"
  )
```

#### Results

Detection probabilities.

```{r}
tar_read_ds("detection_probabilities", params$species) %>%
  filter(year == params$year) %>%
  select(-species, -year) %>%
  drop_na() %>%
  relocate("estimate_p", "se_p", "ll_beta", "ul_beta", .after = last_col()) %>%
  kable()
```

###### Stratum

Abundances.

```{r}
abundances_stratum_target <- tar_read_ds("abundances_stratum", params$species)
abundances_stratum <- abundances_stratum_target %>%
  filter(
    if (params$year == 2023) {
      year == params$year & grepl("^Zandleem|^Leem", Label)
    } else {
      year == params$year
    }
  ) %>%
  select(-species, -year) %>%
  rename("stratum" = "Label", "estimate" = "Estimate")
abundances_stratum %>%
  kable()
```

Densities.

```{r}
densities_stratum_target <- tar_read_ds("densities_stratum", params$species)
densities_stratum <- densities_stratum_target %>%
  filter(
    if (params$year == 2023) {
      year == params$year & grepl("^Zandleem|^Leem", Label)
    } else {
      year == params$year
    }
  ) %>%
  select(-species, -year) %>%
  rename("stratum" = "Label", "estimate" = "Estimate")
densities_stratum %>%
  kable()
```

```{r}
densities_stratum %>%
  separate(stratum, into = c("regio", "openheid", "sbp"), sep = " - ") %>%
  mutate(stratum = paste(openheid, sbp, sep = " - ")) %>%
  ggplot(aes(x = openheid, y = estimate, colour = sbp)) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = lcl, ymax = ucl),
    width = 0.2,
    position = position_dodge(width = 0.5)
  ) +
  scale_y_continuous(limits = c(0, NA)) +
  labs(y = "breeding pairs / 100 ha", x = "") +
  facet_wrap(~regio, ncol = 2, scales = "free")
```

###### Region

Abundances.

```{r}
abundances_region_target <- tar_read_ds("abundances_region", params$species)
abundances_region <- abundances_region_target %>%
  filter(
    if (params$year == 2023) {
      year == params$year & grepl("^Zandleem|^Leem", Label)
    } else {
      year == params$year
    }
  ) %>%
  select(-species, -year) %>%
  rename("region" = "Label", "estimate" = "Estimate")
abundances_region %>%
  kable()
```

Densities.

```{r}
densities_region_target <- tar_read_ds("densities_region", params$species)
densities_region <- densities_region_target %>%
  filter(
    if (params$year == 2023) {
      year == params$year & grepl("^Zandleem|^Leem", Label)
    } else {
      year == params$year
    }
  ) %>%
  select(-species, -year) %>%
  rename("region" = "Label", "estimate" = "Estimate")
densities_region %>%
  kable()
```

```{r}
densities_region %>%
  filter(region != "Total") %>%
  ggplot(aes(x = region, y = estimate)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = lcl, ymax = ucl), width = 0.2, linewidth = 1) +
  scale_y_continuous(limits = c(0, NA), breaks = seq(0, 100, 2)) +
  labs(y = "breeding pairs / 100 ha", x = "")
```
