
```{r}
# packages
library(tidyverse)
library(targets)
library(Distance)

library(INBOtheme)
theme_set(theme_inbo(transparent = TRUE))

# Conflicts
conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::select)

# Paths
mbag_dir <- rprojroot::find_root_file(criterion = rprojroot::is_git_root)

# Source functions
source(file.path(mbag_dir, "source", "R", "tar_read_ds.R"))
source(file.path(mbag_dir, "source", "R", "plot_pdf_per_cat.R"))
source(file.path(mbag_dir, "source", "R", "plot_detection_curve.R"))
```

## `r params$species`

```{r, results='asis'}
for (y in params$years) {
  params$year <- y

  out <- capture.output({
    child <- knitr::knit_child(
      file.path(here::here(), "ds_per_year.Rmd"),
      envir = knit_global()
    )
  })
  cat(child, sep = "\n")
}
```

### Densiteiten over de jaren

```{r}
densities_stratum_target <- tar_read_ds("densities_stratum", params$species)
densities_stratum_target %>%
  filter(
    year == 2023 & grepl("^Zandleem|^Leem", Label) | year != 2023
  ) %>%
  rename("stratum" = "Label", "estimate" = "Estimate") %>%
  filter(stratum != "Total") %>%
  separate(stratum, into = c("regio", "openheid", "sbp"), sep = " - ") %>%
  mutate(stratum = paste(openheid, sbp, sep = " - ")) %>%
  ggplot(aes(x = year, y = estimate, colour = stratum)) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = lcl, ymax = ucl),
    width = 0.2,
    position = position_dodge(width = 0.5)
  ) +
  scale_y_continuous(limits = c(0, NA)) +
  labs(y = "breeding pairs / 100 ha", x = "") +
  facet_wrap(~regio, ncol = 2, scales = "free")
```

```{r}
densities_region_target <- tar_read_ds("densities_region", params$species)
densities_region_target %>%
  filter(
    year == 2023 & grepl("^Zandleem|^Leem", Label) | year != 2023
  ) %>%
  rename("region" = "Label", "estimate" = "Estimate") %>%
  filter(region != "Total") %>%
  ggplot(aes(x = year, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = lcl, ymax = ucl),
    width = 0.2,
  ) +
  scale_y_continuous(limits = c(0, NA)) +
  labs(y = "breeding pairs / 100 ha", x = "") +
  facet_wrap(~region, ncol = 2, scales = "free")
```
