---
title: "Procedure om data te downloaden van de SOVON WFS service en verwerking via targets pipeline"
author: "Hans Van Calster & Ward Langeraert"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Download data via SOVON WFS service
## QGIS v3.24

1.  een account aanmaken via <https://www.vogelatlas.be/user/newuser>

    1.   Rechten aanvragen Sovon

1.  open QGIS
    
    1. Zet project crs op EPSG:28992
    1. Kies `Kaartlagen` --\> `Databronnen beheren` --\> `WFS / OGC API objecten`

1.  klik `nieuw` in het dialoogvenster om een nieuwe WFS verbinding te maken

    1.   Gebruik als naam `sovon` en als url `https://portal.sovon.nl/views/wfs/453/`
    1.   Klik op OK

1.  Maak een verbinding met de zopas toegevoegde WFS service

    1.   Klik op verbinden
    1.   Selecteer de laag `ms:viewpoints`
         -  Vraag een query aan voor data van het nieuwe jaar, bv.: `SELECT * FROM viewpoints WHERE jaar = 2024`
    1.   Vink het boxje aan 'Alleen objecten bevragen die het huidige zichtbare bereik overlappen'
    1.   Klik op toevoegen
    1.   Geef je gebruikersnaam en paswoord
    1.   Indien QGIS vraagt voor transformatie van EPSG:28992 naar een ander CRS, kan je dit best cancellen

Als alles goed gaat, worden nu alle data waar je toegang toe hebt gedownload (dit kan even duren).
Dit zijn de zogenaamde bezoekstippen.

## QGIS v3.26

1.  een account aanmaken via <https://www.vogelatlas.be/user/newuser>

    1.   Rechten aanvragen Sovon

1.  open QGIS
    
    1. Zet project crs op EPSG:28992
    1. Kies `Kaartlagen` --\> `Databronnen beheren` --\> `WFS / OGC API objecten`

1.  klik `nieuw` in het dialoogvenster om een nieuwe WFS verbinding te maken

    1.   Gebruik als naam `sovon` en als url `https://portal.sovon.nl/views/wfs/453/`
    1.   Klik op OK

1.  Maak een verbinding met de zopas toegevoegde WFS service

    1.   Klik op Verbinden
    1.   Geef je gebruikersnaam en paswoord en kik op ok
    1.   Selecteer de laag `ms:viewpoints`
         -  Vraag een query aan voor data van het nieuwe jaar, bv.: `SELECT * FROM viewpoints WHERE jaar = 2024`
    1.   Vink het boxje aan 'Alleen objecten bevragen die het huidige zichtbare bereik overlappen'
    1.   Wijzig Coördinaten Referentiesysteem naar EPSG:28992
    1.   Klik op toevoegen
    1.   Indien QGIS vraagt voor transformatie van EPSG:28992 naar een ander CRS, kan je dit best cancellen

Als alles goed gaat, worden nu alle data waar je toegang toe hebt gedownload (dit kan even duren).
Dit zijn de zogenaamde bezoekstippen.

# Exporteren en verwerking van de data

Wanneer alle data gedownload zijn, kan je deze laag exporteren:

1.  Zorg dat alle data zichtbaar zijn in de view

2.  Selecteer `Kaartlagen` --\> `Opslaan als ...` en sla op als `Geojson` (of `Geopackage`) met als bestandsnaam `<YYYYMMDD_qgis_export_sovon_wfs>` en CRS `EPSG:28992`.
    Klik op OK (dit kan even duren).
