# Source functions
scripts <- list.files(
  path = "R",
  pattern = "^autoqmd.*\\.R$",
  full.names = TRUE
)
invisible(lapply(scripts, source))

# Clean report file and remove child files
message <- c(
  "",
  "> Niet manueel aanpassen"
)

autoqmd_finalise(
  target_files = "04_schatting_simulatieparameters.qmd",
  message = message,
  child_dirs_rm = "child_qmd"
)

autoqmd_finalise(
  target_files = "zzz_visualisatie_poweroptimalisatie.qmd",
  message = message,
  child_dirs_rm = "child_qmd2",
  start_marker = "<!-- AUTOGENERATED-START2 -->",
  end_marker = "<!-- AUTOGENERATED-END2 -->"
)

# Flanders qmd post render
flandersqmd::post_render()
