# remotes::install_github("inbo/flandersqmd#57a604d981d85d632db65c98b1abb2e9d032359c") # nolint: commented_code_linter, line_length_linter
library(flandersqmd)

message <- c(
  "",
  "> Niet manueel aanpassen"
)

# Clean report file and remove child files
autoqmd_finalise(
  target_files = "04_schatting_simulatieparameters.qmd",
  message = message,
  child_dirs_rm = "child_qmd"
)

autoqmd_finalise(
  target_files = "appendix.qmd",
  message = message,
  child_dirs_rm = "child_qmd2",
  start_marker = "<!-- AUTOGENERATED-START2 -->",
  end_marker = "<!-- AUTOGENERATED-END2 -->"
)

# Flanders qmd post render
flandersqmd::post_render()
