---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Detecteerbare effectgrootte {#sec-detecteerbare-effectgrootte}
## Resultaten

```{r}
#| echo: FALSE
#| warning: FALSE
#| message: FALSE
library(knitr)
library(targets)
library(tidyverse)
library(glmmTMB)

conflicted::conflicts_prefer(dplyr::filter)

source("R/tar_read_mas.R")
```

```{r}
target_species <- c(
  "Boerenzwaluw",
  "Geelgors",
  "Gele Kwikstaart",
  "Grasmus",
  "Graspieper",
  "Grutto",
  "Kievit",
  "Kneu",
  "Patrijs",
  "Ringmus",
  "Roodborsttapuit",
  "Scholekster",
  "Torenvalk",
  "Veldleeuwerik",
  "Wulp"
)
```

```{r}
# Get effect sizes
detectable_effect_df <- lapply(target_species, function(spec) {
  tryCatch({
    tar_read_mas("detectable_effect_df", species = spec)
  }, error = function(e) {
    NULL
  })
}) %>%
  bind_rows()
```

```{r}
detectable_effect_df %>%
  ggplot(aes(x = n_telpunten, y = effect_pct, colour = species)) +
  geom_line(linewidth = 0.3) +
  geom_point(size = 1) +
  geom_errorbar(
    aes(
      ymin = effect_pct_low,
      ymax = effect_pct_high
    ),
    width = 5, linewidth = 0.3
  ) +
  labs(
    x = "Aantal telpunten",
    y = "Detecteerbare jaarlijkse\ninteractieverandering (%)",
    colour = "Soort"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r}
#| warning: FALSE
#| message: FALSE
detectable_effect_df %>%
  ggplot(aes(x = sigma_punt, y = effect_pct,
             colour = factor(n_telpunten), group = factor(n_telpunten))) +
  geom_point(size = 1) +
  geom_errorbar(
    aes(
      ymin = effect_pct_low,
      ymax = effect_pct_high
    ),
    width = 0.07, linewidth = 0.3
  ) +
  geom_smooth(method = "lm", formula = "y ~ x", linewidth = 0.3, se = FALSE) +
  labs(
    x = "Variabiliteit telpunten (sigma_punt)",
    y = "Detecteerbare jaarlijkse\ninteractieverandering (%)",
    colour = "Aantal telpunten"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

```{r}
#| warning: FALSE
#| message: FALSE
detectable_effect_df %>%
  ggplot(aes(x = exp(beta_0), y = effect_pct,
             colour = factor(n_telpunten), group = factor(n_telpunten))) +
  geom_point(size = 1) +
  geom_errorbar(
    aes(
      ymin = effect_pct_low,
      ymax = effect_pct_high
    ),
    width = 0.005, linewidth = 0.3
  ) +
  geom_smooth(method = "lm", formula = "y ~ x", linewidth = 0.3, se = FALSE) +
  labs(
    x = "Startdensiteit (exp(beta_0))",
    y = "Detecteerbare jaarlijkse\ninteractieverandering (%)",
    colour = "Aantal telpunten"
  ) +
  theme_minimal() +
  theme(legend.position = "bottom")
```
