project:
  type: book
  render:
  - '*.md'
  - '*.qmd'
  - '!LICENSE.md'
  - '!README.md'
  output-dir: ../../../output/rapporten/power_mas_light
  pre-render: R/pre_render.R
  post-render: _extensions/inbo/flandersqmd-book/filters/post_render.R

execute:
  echo: false
  warnings: true
  errors: true
  message: true
  freeze: false
  cache: false

format:
  flandersqmd-book-pdf: default

lang: nl-BE

flandersqmd:
  entity: INBO
  level: 2
  public_report: false
  colophon: false

  title: Poweranalyse voor het meten van de effectiviteit van soortenbeschermingsprogramma’s
    in landbouwgebied van Vlaanderen
  subtitle: Aanzet tot een vereenvoudigde versie van het Meetnet Agrarische Soorten
    (“MAS light”)
  shorttitle: power-mas-light

  author:
  - name:
      given: Ward
      family: Langeraert
    email: ward.langeraert@inbo.be
    orcid: 0000-0002-5900-8109
    affiliation:
    - Instituut voor Natuur- en Bosonderzoek (INBO)
    corresponding: true

  reviewer:
  - name:
      given: Thierry
      family: Onkelinx
    email: thierry.onkelinx@inbo.be
    orcid: 0000-0001-8804-4216
    affiliation:
    - Instituut voor Natuur- en Bosonderzoek (INBO)

  year: 2026
  reportnr: internal

  linenr: false
  watermark:

book:
  chapters:
  - index.md
  - 02_inleiding.md
  - 03_methodiek.qmd
  - 04_schatting_simulatieparameters.qmd
  - 05_detecteerbare_effectgrootte.qmd
  - 06_conclusie.md
  - referenties.md

bibliography: references.bib
