#' Insert autogenerated child includes into a QMD file
#'
#' This function replaces the lines between
#' \code{<!-- AUTOGENERATED-START -->} and
#' \code{<!-- AUTOGENERATED-END -->} in a Quarto (\code{.qmd}) file
#' with a set of child includes. Each include is written as
#' \code{{< include path >}} in a new line.
#'
#' @param qmd_file Path to the Quarto file to modify.
#' @param child_files Character vector of file paths to include.
#' @param start_marker Marker string indicating the start of the autogenerated
#' block. Defaults to \code{"<!-- AUTOGENERATED-START -->"}.
#' @param end_marker Marker string indicating the end of the autogenerated
#' block. Defaults to \code{"<!-- AUTOGENERATED-END -->"}.
#' @param quiet Logical; if \code{TRUE}, suppresses messages.
#'
#' @return Invisibly returns the modified lines of the QMD file.
#'   The file is updated on disk.
add_autogenerated_includes <- function(
    qmd_file,
    child_files,
    start_marker = "<!-- AUTOGENERATED-START -->",
    end_marker   = "<!-- AUTOGENERATED-END -->",
    quiet = FALSE
) {
  # Read QMD
  lines <- readLines(qmd_file)

  # Find markers
  start <- grep(start_marker, lines)
  end   <- grep(end_marker, lines)
  if (length(start) != 1 || length(end) != 1 || start > end) {
    stop("Markers not found or malformed in QMD file: ", qmd_file)
  }

  # Build child includes
  child_lines <- sprintf("{{< include %s >}}\n", child_files)

  # Replace block
  lines_new <- c(
    lines[1:start],
    "",
    child_lines,
    lines[end:length(lines)]
  )

  # Write back
  writeLines(lines_new, qmd_file)

  if (!quiet) {
    message("Updated autogenerated block in ", qmd_file,
            " with ", length(child_files), " child includes.")
  }

  invisible(lines_new)
}
