#' Insert autogenerated child includes into a QMD file with optional page breaks
#'
#' This function replaces the lines between
#' \code{<!-- AUTOGENERATED-START -->} and
#' \code{<!-- AUTOGENERATED-END -->} in a Quarto (\code{.qmd}) file
#' with a set of child includes. Each include is written as
#' \code{{< include path >}} on a new line. Optionally, LaTeX page
#' breaks (\code{\newpage} or \code{\clearpage}) can be inserted
#' between includes.
#'
#' @param qmd_file Path to the Quarto file to modify.
#' @param child_files Character vector of file paths to include.
#' @param start_marker Marker string indicating the start of the autogenerated
#' block. Defaults to \code{"<!-- AUTOGENERATED-START -->"}.
#' @param end_marker Marker string indicating the end of the autogenerated
#' block. Defaults to \code{"<!-- AUTOGENERATED-END -->"}.
#' @param page_break Character string specifying a LaTeX page break to
#' insert between includes. Options: \code{"newpage"}, \code{"clearpage"}.
#' Defaults to \code{NULL} (no page breaks).
#' @param quiet Logical; if \code{TRUE}, suppresses messages.
#'
#' @return Invisibly returns the modified lines of the QMD file.
#'   The file is updated on disk.
#' @export
#'
#' @examples
#' \dontrun{
#' add_autogenerated_includes(
#'   qmd_file = "report.qmd",
#'   child_files = c("intro.qmd", "results.qmd", "discussion.qmd"),
#'   page_break = "clearpage"
#' )
#' }
add_autogenerated_includes <- function(
    qmd_file,
    child_files,
    start_marker = "<!-- AUTOGENERATED-START -->",
    end_marker   = "<!-- AUTOGENERATED-END -->",
    page_break   = NULL,
    quiet = FALSE
) {
  # Validate page_break
  if (!is.null(page_break) && !page_break %in% c("newpage", "clearpage")) {
    stop("page_break must be NULL, 'newpage', or 'clearpage'.")
  }

  # Read QMD file
  lines <- readLines(qmd_file)

  # Find markers
  start <- grep(start_marker, lines)
  end   <- grep(end_marker, lines)
  if (length(start) != 1 || length(end) != 1 || start > end) {
    stop("Markers not found or malformed in QMD file: ", qmd_file)
  }

  # Build child includes
  if (!is.null(page_break)) {
    # Insert page break between includes, but not after the last one
    include_lines <- paste0("{{< include ", child_files, " >}}")
    child_lines <- paste(
      paste(include_lines, collapse = paste0("\n\n\\", page_break, "\n\n")),
      "\n"
    )
  } else {
    child_lines <- sprintf("{{< include %s >}}\n", child_files)
  }

  # Replace block between markers
  lines_new <- c(
    lines[1:start],
    "",
    child_lines,
    lines[end:length(lines)]
  )

  # Write back to file
  writeLines(lines_new, qmd_file)

  if (!quiet) {
    msg <- paste0("Updated autogenerated block in ", qmd_file,
                  " with ", length(child_files), " child includes.")
    if (!is.null(page_break)) msg <- paste0(msg, " Page breaks added: \\", page_break, ".")
    message(msg)
  }

  invisible(lines_new)
}
