#' Insert autogenerated child includes into a QMD file with optional page breaks
#'
#' This function replaces the lines between
#' `<!-- AUTOGENERATED-START -->` and
#' `<!-- AUTOGENERATED-END -->` in a Quarto (`.qmd`) file
#' with a set of child includes. Each include is written as
#' `{< include path >}` on a new line. Optionally, LaTeX page
#' breaks (`\newpage` or `\clearpage`) can be inserted
#' between includes.
#'
#' If a template file timestamp is available (via the `template`
#' attribute in the environment or as an argument), it is written
#' as an invisible HTML comment before the first include. This ensures
#' that Quarto's `freeze` mechanism detects updates when the template changes,
#' even if the parent QMD file’s visible content is unchanged.
#'
#' @param qmd_file Path to the Quarto file to modify.
#' @param child_files Character vector of file paths to include.
#' @param start_marker Marker string indicating the start of the autogenerated
#' block. Defaults to `"<!-- AUTOGENERATED-START -->"`.
#' @param end_marker Marker string indicating the end of the autogenerated
#' block. Defaults to `"<!-- AUTOGENERATED-END -->"`.
#' @param page_break Character string specifying a LaTeX page break to
#' insert between includes. Options: `"newpage"`, `"clearpage"`.
#' Defaults to `NULL` (no page breaks).
#' @param template Optional path to the QMD template used to generate
#' the child files. If provided, its modification time is inserted as a
#' hidden timestamp comment to trigger Quarto rebuilds when updated.
#' @param quiet Logical; if `TRUE`, suppresses messages.
#'
#' @return Invisibly returns the modified lines of the QMD file.
#'   The file is updated on disk.
autoqmd_insert_includes <- function( # nolint: cyclocomp_linter
  qmd_file,
  child_files,
  start_marker = "<!-- AUTOGENERATED-START -->",
  end_marker = "<!-- AUTOGENERATED-END -->",
  page_break = NULL,
  template = NULL,
  quiet = FALSE
) {
  # Validate page_break
  if (!is.null(page_break) && !page_break %in% c("newpage", "clearpage")) {
    stop("page_break must be NULL, 'newpage', or 'clearpage'.")
  }

  # Read QMD file
  lines <- readLines(qmd_file)

  # Find markers
  start <- grep(start_marker, lines)
  end   <- grep(end_marker, lines)
  if (length(start) != 1 || length(end) != 1 || start > end) {
    stop("Markers not found or malformed in QMD file: ", qmd_file)
  }

  # Template timestamp comment
  if (!is.null(template) && file.exists(template)) {
    template_mtime <- format(file.info(template)$mtime, "%Y-%m-%d %H:%M:%S")
    timestamp_line <- sprintf("<!-- TEMPLATE-MTIME: %s -->", template_mtime)
  } else {
    timestamp_line <- sprintf("<!-- TEMPLATE-MTIME: %s -->", Sys.time())
  }

  # Build child includes
  if (!is.null(page_break)) {
    # Insert page break between includes, but not after the last one
    include_lines <- paste0("{{< include ", child_files, " >}}")
    child_lines <- paste(
      paste(include_lines, collapse = paste0("\n\n\\", page_break, "\n\n")),
      "\n"
    )
  } else {
    child_lines <- sprintf("{{< include %s >}}\n", child_files)
  }

  # Combine the hidden timestamp and includes
  autogenerated_block <- c(timestamp_line, "", child_lines)

  # Replace block between markers
  lines_new <- c(
    lines[1:start],
    "",
    autogenerated_block,
    lines[end:length(lines)]
  )

  # Write back to file
  writeLines(lines_new, qmd_file)

  if (!quiet) {
    msg <- paste0("Updated autogenerated block in ", qmd_file,
                  " with ", length(child_files), " child includes.")
    if (!is.null(page_break)) {
      msg <- paste0(msg, " Page breaks added: \\", page_break, ".")
    }
    message(msg)
  }

  invisible(lines_new)
}
