#' Replace autogenerated section in a QMD file with a custom message
#'
#' This function post-processes a Quarto (`.qmd`) file by replacing the
#' section between specified start and end markers with a custom message. It is
#' useful for ensuring that autogenerated content is clearly marked and
#' preventing manual edits in those sections.
#'
#' @param qmd_file Character string. Path to the QMD file to modify.
#' @param message Character vector. The message to insert between the start
#' and end markers. Each element of the vector is written as a separate line.
#' @param start_marker Character string. The marker indicating where the
#' autogenerated section starts. Defaults to
#' `"<!-- AUTOGENERATED-START -->"`.
#' @param end_marker Character string. The marker indicating where the
#' autogenerated section ends. Defaults to `"<!-- AUTOGENERATED-END -->"`.
#'
#' @return Invisibly returns the modified lines as a character vector.
#'   The QMD file is also overwritten on disk.
autoqmd_cleanup <- function(
  qmd_file,
  message,
  start_marker = "<!-- AUTOGENERATED-START -->",
  end_marker   = "<!-- AUTOGENERATED-END -->"
) {
  # Read the file contents
  lines <- readLines(qmd_file)

  # Locate markers for autogenerated section
  start <- grep(start_marker, lines)
  end   <- grep(end_marker, lines)

  # Validate marker positions
  if (length(start) != 1 || length(end) != 1 || start > end) {
    stop("Markers not found or malformed in QMD")
  }

  # Construct updated file content:
  # - Keep everything up to the start marker
  # - Insert the warning message
  # - Keep everything from the end marker onward
  lines_new <- c(
    lines[1:start],
    message,
    "",
    lines[end:length(lines)]
  )

  # Write modified lines back to file
  writeLines(lines_new, qmd_file)

  invisible(lines_new)
}
