library(knitr)
library(dplyr)
library(targets)

source(file.path("scripts", "generate_species_qmd.R"))
source(file.path("scripts", "add_autogenerated_includes.R"))

# Globals
species_vec <- sort(
  c(
    "Geelgors",
    "Gele Kwikstaart",
    "Grasmus",
    "Graspieper",
    "Grutto",
    "Kievit",
    "Kneu",
    "Patrijs",
    "Ringmus",
    "Roodborsttapuit",
    "Scholekster",
    "Torenvalk",
    "Veldleeuwerik",
    "Wulp"
  )
)

mbag_dir <- rprojroot::find_root_file(criterion = rprojroot::is_git_root)
store <- file.path(mbag_dir, "source", "targets", "data_preparation",
                   "_targets")
taxa_df <- tar_read("manual_taxon_mapping", store = store)

# -------------------------------
# 1. Define species and generate child QMDs
# -------------------------------
# Get scientific names
sci_names <- taxa_df %>%
  dplyr::filter(dwc_vernacularName %in% species_vec) %>%
  distinct(dwc_vernacularName, species) %>%
  arrange(dwc_vernacularName) %>%
  pull(species)

# Species densities
out_files_dens <- generate_species_qmd(
  species = species_vec,
  label = gsub("\\s", ".", tolower(species_vec)),
  sci_name = sci_names,
  template = "_species_densities.qmd",
  suffix = "",
  spec_dir = "spec_files"
)

# Appendix detection curves
out_files_detcurve <- generate_species_qmd(
  species = species_vec,
  label = gsub("\\s", ".", tolower(species_vec)),
  template = "_species_detectioncurves.qmd",
  suffix = "2",
  spec_dir = "spec_files"
)

# Appendix density tables
out_files_densstratum <- generate_species_qmd(
  species = species_vec,
  label = gsub("\\s", ".", tolower(species_vec)),
  template = "_densities_tables.qmd",
  suffix = "3",
  spec_dir = "spec_files"
)

# -------------------------------
# 2. Modify main QMD
# -------------------------------
# Species densities
add_autogenerated_includes(
  qmd_file = "09_densiteitsschattingen.qmd",
  child_files = out_files_dens,
  page_break = "clearpage",
  quiet = FALSE
)

# Appendix detection curves
add_autogenerated_includes(
  qmd_file = "detection_curves.qmd",
  child_files = out_files_detcurve,
  quiet = FALSE
)

# Appendix density tables
add_autogenerated_includes(
  qmd_file = "densities_tables.qmd",
  child_files = out_files_densstratum,
  page_break = "newpage",
  quiet = FALSE
)
