# Load functions
library(knitr)
library(dplyr)
library(targets)

source(file.path("scripts", "autoqmd_generate_children.R"))
source(file.path("scripts", "autoqmd_insert_includes.R"))

# Helper functions
firstup <- function(name) {
  paste0(
    toupper(substr(name, 1, 1)),
    tolower(substr(name, 2, nchar(name)))
  )
}

# Wrapper for child documents
autoqmd_prepare <- function(
  ...,
  template,
  child_dir,
  freeze = NULL,
  qmd_file,
  start_marker = "<!-- AUTOGENERATED-START -->",
  end_marker   = "<!-- AUTOGENERATED-END -->",
  page_break   = NULL,
  quiet = FALSE
) {
  child_files <- autoqmd_generate_children( # nolint: object_usage_linter
    ...,
    template = template,
    child_dir = child_dir,
    freeze = freeze
  )

  autoqmd_insert_includes( # nolint: object_usage_linter
    qmd_file = qmd_file,
    child_files = child_files,
    start_marker = start_marker,
    end_marker = end_marker,
    page_break = page_break,
    template = template,
    quiet = quiet
  )
}

# Globals
species_vec <- sort(
  c(
    "Geelgors",
    "Gele Kwikstaart",
    "Grasmus",
    "Graspieper",
    "Grutto",
    "Kievit",
    "Kneu",
    "Patrijs",
    "Ringmus",
    "Roodborsttapuit",
    "Scholekster",
    "Torenvalk",
    "Veldleeuwerik",
    "Wulp"
  )
)

mbag_dir <- rprojroot::find_root_file(criterion = rprojroot::is_git_root)
store <- file.path(mbag_dir, "source", "targets", "data_preparation",
                   "_targets")
taxa_df <- tar_read("manual_taxon_mapping", store = store)

# Get scientific names
sci_names <- taxa_df %>%
  dplyr::filter(dwc_vernacularName %in% species_vec) %>%
  distinct(dwc_vernacularName, species) %>%
  arrange(dwc_vernacularName) %>%
  pull(species)

# -------------------------------
# Prepare child documents and add to qmd
# -------------------------------

# Species densities
autoqmd_prepare(
  species = species_vec,
  specname_cap = firstup(species_vec),
  specname_low = tolower(species_vec),
  label = gsub("\\s", ".", tolower(species_vec)),
  sci_name = sci_names,
  template = "_species_densities.qmd",
  child_dir = "spec_files",
  freeze = "label",
  qmd_file = "09_densiteitsschattingen.qmd",
  page_break = "clearpage",
  quiet = FALSE
)

# Appendix detection curves
autoqmd_prepare(
  species = species_vec,
  specname_cap = firstup(species_vec),
  specname_low = tolower(species_vec),
  label = gsub("\\s", ".", tolower(species_vec)),
  template = "_species_detectioncurves.qmd",
  child_dir = "spec_files2",
  qmd_file = "detection_curves.qmd",
  quiet = FALSE
)

# Appendix density tables
autoqmd_prepare(
  species = species_vec,
  specname_cap = firstup(species_vec),
  specname_low = tolower(species_vec),
  label = gsub("\\s", ".", tolower(species_vec)),
  template = "_densities_tables.qmd",
  child_dir = "spec_files2",
  qmd_file = "densities_tables.qmd",
  page_break = "newpage",
  quiet = FALSE
)
