on:
  push:
    branches-ignore:
      - gh-pages

name: check-project

jobs:
  check-src:
    runs-on: ubuntu-latest
    name: "check project with checklist"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
    steps:
      - name: "Check project with checklist"
        uses: inbo/actions/check_project@main
        with:
          path: "."
          cmd: |
            sudo apt-get update
            sudo apt-get install --yes \
              libgdal-dev \
              libgeos-dev \
              libproj-dev \
              libpoppler-cpp-dev \
              libglpk-dev \
              libsecret-1-dev \
              libudunits2-dev
