book_filename: "langeraert_et_al_mas_uitrol_vlaanderen.Rmd"
output_dir: "../../../output/rapporten"
delete_merged_file: TRUE
language:
  label:
    fig:    'Figuur '
    tab:    'Tabel '
    eq:     'Vergelijking '
    thm:    'Theorema '
    lem:    'Lemma '
    def:    'Definitie '
    cor:    'Gevolgtrekking '
    prp:    'Bewering '
    ex:     'Voorbeeld '
    proof:  'Bewijs. '
    remark: 'Opmerking. '
