project:
  type: book
  preview:
    port: 4201
    browser: true
  render:
  - '*.md'
  - '*.qmd'
  - '!LICENSE.md'
  - '!README.md'
  output-dir: "../../../output/rapporten/mas_uitrol_vlaanderen"
  post-render: _extensions/inbo/flandersqmd-book/filters/post_render.R

execute:
  echo: false
  warnings: true
  errors: true
  message: true
  freeze: false
  cache: false

lang: nl-BE

bibliography: [software.bib, references.bib, layers.bib]

format:
  flandersqmd-book-html: default
  flandersqmd-book-pdf: default

flandersqmd:
  entity: INBO
  level: 2
  title: "Uitrol van een Meetnet Agrarische Soorten in Vlaanderen"
  subtitle: "Achtergronddocument Meetnet Agrarische Soorten in kader van het Meetnet Biodiversiteit in Agrarisch Gebied (MBAG project)"
  shorttitle: mas-uitrol-vlaanderen
  author:
  - name:
      given: "Ward"
      family: "Langeraert"
    email: "ward.langeraert@inbo.be"
    orcid: "0000-0002-5900-8109"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
    corresponding: true
  - name:
      given: "Emma"
      family: "Cartuyvels"
    email: "emma.cartuyvels@inbo.be"
    orcid: "0000-0001-7856-6360"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Simon"
      family: "Desmet"
    email: "simon.desmet@inbo.be"
    orcid: "0009-0006-0433-7593"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Hans"
      family: "Van Calster"
    email: "hans.vancalster@inbo.be"
    orcid: "0000-0001-8595-8426"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Nicolas"
      family: "Van Overmeeren"
    email: "nicolas.vanovermeeren@inbo.be"
    orcid: "0009-0005-2174-672X"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Johannes"
      family: "Jansen"
    email: "johannes.jansen@inbo.be"
    orcid: "0009-0005-2436-5236"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  reviewer:
  - name:
      given: "Koen"
      family: "Devos"
    email: "koen.devos@inbo.be"
    orcid: "0000-0001-7265-6349"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  - name:
      given: "Olivier"
      family: "Dochy"
    email: "olivier.dochy@inbo.be"
    orcid: "0009-0002-2822-5634"
    affiliation: "Instituut voor Natuur- en Bosonderzoek (INBO)"
  year: 2025
  #reportnr:
  #cover:
  #coverphoto:
  #coverdescription:
  #ordernr: optional order number
  #depotnr: optional depot number
  public_report: true
  colophon: true
  floatbarrier: section

book:
  downloads: pdf
  open-graph: true
  body-footer: '{{< footer >}}'
  navbar:
    pinned: true
    right:
    - icon: mastodon
      href: https://mastodon.online/&#64;inbo
    - icon: bluesky
      href: https://bsky.app/profile/inbo.be
    - icon: facebook
      href: https://www.facebook.com/INBOVlaanderen/
    - icon: github
      menu:
        - text: Source Code
          url:  https://github.com/inbo/mbag-mas
        - text: Report a Bug
          url:  https://github.com/inbo/mbag-mas/issues
    left:
    - text: Cover
      file: index.md
    - text: Samenvatting (NL)
      file: 01_samenvatting.md
    - text: Abstract (EN)
      file: 02_abstract.md
    - text: Aanbevelingen
      file: 03_aanbevelingen.md
    - text: Inleiding
      file: 04_inleiding.qmd
  chapters:
  - index.md
  - 01_samenvatting.md
  - 02_abstract.md
  - 03_aanbevelingen.md
  - 04_inleiding.qmd
  - 05_uitrol_meetnet.qmd
  - 06_analyse_plan.qmd
  - 07_resultaten.qmd
  - 08_discussie.qmd
  - 09_referenties.md
  appendices:
    - kaarten_sbp.qmd
