### {{species}}

```{r}
#| include: FALSE
# set up
library(knitr)
opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  out.width = "100%"
)
```

```{r}
# packages
library(tidyverse)
library(targets)
library(sf)
library(Distance)
library(patchwork)
library(kableExtra)

library(INBOtheme)
theme_set(theme_inbo(transparent = TRUE))

# Conflicts
conflicted::conflicts_prefer(dplyr::filter)
conflicted::conflicts_prefer(dplyr::select)

# Paths
mbag_dir <- rprojroot::find_root_file(criterion = rprojroot::is_git_root)
store <- file.path(mbag_dir,
                   "source", "targets", "distance_sampling", "_targets")

# Source functions
source(file.path(mbag_dir, "source", "R", "tar_read_ds.R"))
source(file.path(mbag_dir, "source", "R", "plot_detection_curve.R"))
source(file.path("scripts", "summarise_detection_patterns.R"))
```

```{r}
# To make it easier
params <- NULL
params$species <- "{{species}}"
#params$species <- "Veldleeuwerik"
```

```{r}
det_prob_df <- tar_read_ds("detection_probabilities", params$species,
                           store = store) %>%
  select(-species) %>%
  replace(is.na(.), "-")

detprob_cap <- paste0("Geschatte detectiekansen ", params$species, ".")
```

De detectiekansen voor `r params$species` (*{{sci_name}}*) zijn weergegeven in @tbl-detprob-{{label}}.
@fig-detprob-{{label}} (@sec-detectiecurve-soort) visualiseert de detectiecurve(s) per jaar. 
`r summarise_detection_patterns(det_prob_df, threshold = 0.05)`

```{r}
#| label: tbl-detprob-{{label}}
#| tbl-cap: "Geschatte detectiekansen {{species}}."
det_prob_df %>%
  mutate(detectiekans = paste0(
    sprintf("%.3f", round(estimate_p, 3)),
    " (",
    sprintf("%.3f", round(ll_beta, 3)),
    "-",
    sprintf("%.3f", round(ul_beta, 3)),
    ")"
  )) %>%
  select("jaar" = "year", any_of(c("regio", "openheid", "sbp")),
         "detectiekans (95 % interval)" = "detectiekans",
         "standaardfout" = "se_p") %>%
  kable(digits = 3, booktabs = TRUE) %>%
  kableExtra::kable_styling(latex_options = "striped") %>%
  kableExtra::row_spec(0, bold = TRUE) %>%
  kableExtra::collapse_rows(1)
```

```{r}
# Get densities
densities_stratum_target <- tar_read_ds("densities_stratum", params$species,
                                        store = store)

# Parse thresholds
threshold_vals <- tibble(
  species = c("Patrijs", "Geelgors", "Veldleeuwerik", "Grauwe Gors"),
  values = c(4, 12.5, 15, 10)
)

# Add effects
if (params$species %in% threshold_vals$species) {
  t <- subset(threshold_vals, species == params$species, "values", drop = TRUE)
  densities_stratum_target <- densities_stratum_target %>%
    mutate(effect = factor(
      case_when(
        lcl > t ~ "boven",
        ucl < t ~ "onder",
        TRUE ~ "geen sign.\nverschil"
      ),
      levels = c("boven", "geen sign.\nverschil", "onder")
    ))
}
```

```{r}
#| label: fig-densstratum-{{label}}
#| fig-cap: "Densiteitsschattingen voor {{species}} per stratum."
#| fig-height: 6
# Prepare base plot data
p <- densities_stratum_target %>%
  filter(
    year == 2023 & grepl("^Zandleem|^Leem", Label) | year != 2023
  ) %>%
  rename("stratum" = "Label", "estimate" = "Estimate") %>%
  filter(stratum != "Total") %>%
  separate(stratum, into = c("regio", "openheid", "sbp"), sep = " - ") %>%
  mutate(stratum = paste(openheid, sbp, sep = " - ")) %>%
  # Initialize ggplot with year on x, estimate on y, grouped by stratum
  ggplot(aes(x = year, y = estimate, group = stratum))

# Plot if species has a defined threshold value
if (params$species %in% threshold_vals$species) {
  # Extract species-specific threshold
  t <- subset(threshold_vals, species == params$species, "values", drop = TRUE)

  p +
    geom_hline(yintercept = t, linetype = "dashed", colour = "darkgrey") +
    geom_errorbar(aes(ymin = lcl, ymax = ucl, colour = stratum),
      width = 0.5,
      position = position_dodge(width = 0.7),
      linewidth = 0.6
    ) +
    geom_point(aes(shape = effect), position = position_dodge(width = 0.7),
               colour = "black", size = 2.5, show.legend = TRUE) +
    scale_y_continuous(limits = c(0, NA)) +
    scale_shape_manual(
      values =  c(0, 2, 4),
      drop = FALSE
    ) +
    labs(y = "broedparen / 100 ha", x = "", colour = "Stratum",
         shape = "Verschil met\nstreefwaarde") +
    facet_wrap(~regio, ncol = 2, scales = "free_x") +
    theme(legend.position = c(0.75, 0.1),
          legend.background = element_rect(fill = "white", color = "darkgrey"),
          legend.margin = margin(6, 6, 6, 6),
          legend.box = "horizontal",
          legend.text = element_text(size = 8)) +
    guides(
      colour = guide_legend(
        override.aes = list(shape = NA, linetype = 1, size = 1)
      ),
      shape = guide_legend(
        override.aes = list(linetype = 0, colour = "black")
      )
    )
} else {
  # If no threshold, simpler plot without horizontal line or shape legend
  p + geom_point(aes(colour = stratum), size = 2,
                 position = position_dodge(width = 0.7)) +
    geom_errorbar(aes(ymin = lcl, ymax = ucl, colour = stratum),
      width = 0.5,
      position = position_dodge(width = 0.7),
      linewidth = 0.6
    ) +
    scale_y_continuous(limits = c(0, NA)) +
    labs(y = "broedparen / 100 ha", x = "", colour = "Stratum") +
    facet_wrap(~regio, ncol = 2, scales = "free_x") +
    theme(legend.position = c(0.75, 0.1),
          legend.background = element_rect(fill = "white", color = "darkgrey"),
          legend.margin = margin(6, 6, 6, 6),
          legend.text = element_text(size = 8))
}
```

```{r}
# Get densities
densities_region_target <- tar_read_ds("densities_region", params$species,
                                       store = store)

# Add effects
if (params$species %in% threshold_vals$species) {
  t <- subset(threshold_vals, species == params$species, "values", drop = TRUE)
  densities_region_target <- densities_region_target %>%
    mutate(effect = factor(
      case_when(
        lcl > t ~ "boven",
        ucl < t ~ "onder",
        TRUE ~ "geen sign.\nverschil"
      ),
      levels = c("boven", "geen sign.\nverschil", "onder")
    ))
}
```

```{r}
#| label: fig-densregio-{{label}}
#| fig-cap: "Densiteitsschattingen voor {{species}} per landbouwregio."
#| fig-height: 6
#| fig-width: 8
# Prepare base plot data
p <- densities_region_target %>%
  filter(
    year == 2023 & grepl("^Zandleem|^Leem", Label) | year != 2023
  ) %>%
  rename("region" = "Label", "estimate" = "Estimate") %>%
  filter(region != "Total") %>%
  # Initialize ggplot with year on x, estimate on y
  ggplot(aes(x = year, y = estimate))

# Plot if species has a defined threshold value
if (params$species %in% threshold_vals$species) {
  # Extract species-specific threshold
  t <- subset(threshold_vals, species == params$species, "values", drop = TRUE)

  p +
    geom_hline(yintercept = t, linetype = "dashed", colour = "darkgrey") +
    geom_point(aes(colour = effect), size = 2.5, show.legend = TRUE) +
    geom_errorbar(
      aes(ymin = lcl, ymax = ucl, colour = effect),
      width = 0.2,
      position = position_dodge(width = 0.7),
      linewidth = 0.8,
      show.legend = TRUE
    ) +
    scale_colour_manual(
      values =  c("chartreuse3",
                  "skyblue",
                  "firebrick1"),
      drop = FALSE
    ) +
    scale_y_continuous(limits = c(0, NA)) +
    labs(y = "broedparen / 100 ha", x = "",
         colour = "Verschil met\nstreefwaarde") +
    facet_wrap(~region, ncol = 2, scales = "free_x")
} else {
  # If no threshold, simpler plot without horizontal line or shape legend
  p +
    geom_point(size = 2.5) +
    geom_errorbar(
      aes(ymin = lcl, ymax = ucl),
      width = 0.2,
      position = position_dodge(width = 0.7),
      linewidth = 0.8,
    ) +
    scale_y_continuous(limits = c(0, NA)) +
    labs(y = "broedparen / 100 ha", x = "") +
    facet_wrap(~region, ncol = 2, scales = "free_x")
}
```
