library(knitr)
library(targets)

# Globals
species <- sort(
  c(
    "Geelgors",
    "Gele Kwikstaart",
    "Grasmus",
    "Graspieper",
    "Grutto",
    "Kievit",
    "Kneu",
    "Patrijs",
    "Ringmus",
    "Roodborsttapuit",
    "Scholekster",
    "Torenvalk",
    "Veldleeuwerik",
    "Wulp"
  )
)
main_qmd <- "09_densiteitsschattingen.qmd"

mbag_dir <- rprojroot::find_root_file(criterion = rprojroot::is_git_root)
store <- file.path(mbag_dir,
                   "source", "targets", "data_preparation", "_targets")
taxa_df <- tar_read("manual_taxon_mapping", store = store)

# -------------------------------
# 1. Define species and generate child QMDs
# -------------------------------
spec_dir <- "spec_files"
dir.create(file.path(spec_dir), showWarnings = FALSE)
output_files <- paste0("_", gsub("\\s", ".", tolower(species)), ".qmd")

for (i in seq_along(species)) {
  spec <- species[i]
  lab <- gsub("\\s", ".", tolower(spec))
  out_file <- output_files[i]

  # Get scientific name
  sci_name <- subset(
    taxa_df,
    dwc_vernacularName == spec,
    select = species,
    drop = TRUE
  )

  knit_expand(
    "_species_densities.qmd", species = spec, sci_name = sci_name, label = lab
  ) |>
    writeLines(file.path(spec_dir, out_file))
}

# -------------------------------
# 2. Modify main QMD
# -------------------------------
# Read the QMD
lines <- readLines(main_qmd)

# Find the lines to replace
start <- grep("<!-- AUTOGENERATED-START -->", lines)
end   <- grep("<!-- AUTOGENERATED-END -->", lines)
if (length(start) != 1 || length(end) != 1 || start > end) {
  stop("Markers not found or malformed in QMD")
}

# Append the child includes as R chunk
child_lines <- sprintf(
  "{{< include %s >}}\n", file.path(spec_dir, output_files)
)
lines_new <- c(
  lines[1:start],
  "",
  child_lines,
  lines[end:length(lines)]
)

# Write back to QMD
writeLines(lines_new, main_qmd)
